#!/bin/sh
# Downloads a prebuilt PDFium shared library from bblanchon/pdfium-binaries and (optionally)
# wires it up for `cargo test --all-features` via a gitignored .cargo/config.toml.
#
# Usage:
#   scripts/fetch-pdfium.sh [--dest DIR] [--write-cargo-config] [--force] [--help]
#
# Env overrides:
#   PDFIUM_VERSION   pdfium-binaries release tag to fetch (default: pinned below)
#
# macOS note: a curl-downloaded dylib carries no com.apple.quarantine attribute, so no `xattr`
# step is needed here. If you instead fetched the tarball with a browser, run
# `xattr -dr com.apple.quarantine <dest>` on it before use.
set -eu

PDFIUM_VERSION="${PDFIUM_VERSION:-chromium/7961}"

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo_root=$(CDPATH= cd -- "$script_dir/.." && pwd)

dest="$repo_root/third_party/pdfium"
write_cargo_config=0
force=0

usage() {
    cat <<EOF
Usage: $0 [--dest DIR] [--write-cargo-config] [--force] [--help]

Downloads a prebuilt, non-V8 PDFium shared library from
https://github.com/bblanchon/pdfium-binaries (pinned to $PDFIUM_VERSION by default; override
with PDFIUM_VERSION=<tag>) and extracts it.

  --dest DIR             Extract into DIR (default: $repo_root/third_party/pdfium)
  --write-cargo-config   Write a gitignored .cargo/config.toml setting PDFSPATIAL_PDFIUM_LIB,
                          so 'cargo test --all-features' works with no shell export.
  --force                Re-download even if the library already exists at --dest.
  --help                 Show this help.
EOF
}

while [ $# -gt 0 ]; do
    case "$1" in
        --dest)
            dest=$2
            shift 2
            ;;
        --dest=*)
            dest=${1#--dest=}
            shift
            ;;
        --write-cargo-config)
            write_cargo_config=1
            shift
            ;;
        --force)
            force=1
            shift
            ;;
        --help | -h)
            usage
            exit 0
            ;;
        *)
            echo "fetch-pdfium.sh: unknown argument: $1" >&2
            usage >&2
            exit 1
            ;;
    esac
done

os=$(uname -s)
arch=$(uname -m)
lib_name=""
asset=""
case "$os" in
    Darwin)
        lib_name="libpdfium.dylib"
        case "$arch" in
            arm64) asset="pdfium-mac-arm64" ;;
            x86_64) asset="pdfium-mac-x64" ;;
        esac
        ;;
    Linux)
        lib_name="libpdfium.so"
        case "$arch" in
            x86_64) asset="pdfium-linux-x64" ;;
            aarch64) asset="pdfium-linux-arm64" ;;
        esac
        ;;
esac

if [ -z "$asset" ]; then
    echo "fetch-pdfium.sh: unsupported platform '$os/$arch'." >&2
    echo "Download a matching release yourself from:" >&2
    echo "  https://github.com/bblanchon/pdfium-binaries/releases/tag/${PDFIUM_VERSION}" >&2
    exit 1
fi

lib_path="$dest/lib/$lib_name"

if [ "$force" -eq 0 ] && [ -f "$lib_path" ]; then
    echo "fetch-pdfium.sh: already present at $lib_path (pass --force to re-download)"
else
    mkdir -p "$dest"
    tmp_tgz=$(mktemp)
    trap 'rm -f "$tmp_tgz"' EXIT

    url="https://github.com/bblanchon/pdfium-binaries/releases/download/${PDFIUM_VERSION}/${asset}.tgz"
    echo "fetch-pdfium.sh: downloading $url"
    curl -fsSL --retry 3 "$url" -o "$tmp_tgz"

    tar -xzf "$tmp_tgz" -C "$dest"

    if [ ! -f "$lib_path" ]; then
        echo "fetch-pdfium.sh: expected library not found at $lib_path after extraction" >&2
        echo "  (archive layout may have changed upstream -- check $dest)" >&2
        exit 1
    fi
fi

echo "fetch-pdfium.sh: PDFium library ready:"
ls -lh "$lib_path"

if [ "$write_cargo_config" -eq 1 ]; then
    cargo_config="$repo_root/.cargo/config.toml"
    marker="# Generated by scripts/fetch-pdfium.sh"
    if [ -f "$cargo_config" ] && ! grep -qF "$marker" "$cargo_config"; then
        echo "fetch-pdfium.sh: $cargo_config already exists and wasn't generated by this script." >&2
        echo "  Refusing to overwrite it. Add this yourself instead:" >&2
        echo "    [env]" >&2
        echo "    PDFSPATIAL_PDFIUM_LIB = \"$lib_path\"" >&2
        exit 1
    fi
    mkdir -p "$repo_root/.cargo"
    cat >"$cargo_config" <<EOF
$marker -- gitignored, machine-specific.
[env]
PDFSPATIAL_PDFIUM_LIB = "$lib_path"
EOF
    echo "fetch-pdfium.sh: wrote $cargo_config"
fi

echo
echo "To use it in a shell without --write-cargo-config, run:"
echo "  export PDFSPATIAL_PDFIUM_LIB=\"$lib_path\""
